# Generated by Django 5.1.2 on 2024-12-30 17:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('poles', models.IntegerField(default=0)),
                ('wcc', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('poles', models.IntegerField(default=0)),
                ('races', models.IntegerField(default=0)),
                ('wdc', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('race_number', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Race', max_length=128)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='racetracker.season')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('poles', models.IntegerField(default=0)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_constructor', to='racetracker.constructor')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_constructors', to='racetracker.season')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='constructors',
            field=models.ManyToManyField(related_name='participated_seasons', through='racetracker.SeasonConstructor', to='racetracker.constructor'),
        ),
        migrations.CreateModel(
            name='SeasonRacer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('poles', models.IntegerField(default=0)),
                ('constructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_racers', to='racetracker.constructor')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_racer', to='racetracker.racer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_racers', to='racetracker.season')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='racers',
            field=models.ManyToManyField(related_name='participated_seasons', through='racetracker.SeasonRacer', to='racetracker.racer'),
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('points_awarded', models.IntegerField()),
                ('dnf', models.BooleanField(default=False)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='racetracker.race')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racetracker.seasonracer')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='QualifyingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying', to='racetracker.race')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racetracker.seasonracer')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
