# Generated by Django 5.1.2 on 2024-12-31 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifyingresult',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying', to='racetracker.race'),
        ),
    ]
