# Generated by Django 5.1.2 on 2025-01-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetracker', '0002_alter_qualifyingresult_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='racer',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
