# Generated by Django 5.1.2 on 2025-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetracker', '0003_alter_constructor_name_alter_racer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
