# Generated by Django 5.1.2 on 2025-06-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetracker', '0004_race_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='wcc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='wdc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
